AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Globals:
  Function:
    Timeout: 3

Parameters:
  HikariCloudApiId:
    Type: String

Resources:
  CreateFolderFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: folder_table
      Events:
        UploadImage:
          Type: Api
          Properties:
            Path: /folder
            Method: POST
            RestApiId: !Ref HikariCloudApiId
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./image/upload
      DockerTag: python3.12-v1

  DeleteFolderFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: folder_table
      Events:
        LoadImage:
          Type: Api
          Properties:
            Path: /folder
            Method: DELETE
            RestApiId: !Ref HikariCloudApiId
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./image/load
      DockerTag: python3.12-v1

  GetFolderFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: folder_table
      Events:
        LoadImage:
          Type: Api
          Properties:
            Path: /folder/{id}
            Method: GET
            RestApiId: !Ref HikariCloudApiId
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./image/load
      DockerTag: python3.12-v1

  UploadPhotoToFolderFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: folder_table
      Events:
        LoadImage:
          Type: Api
          Properties:
            Path: /folder/{id}/upload
            Method: POST
            RestApiId: !Ref HikariCloudApiId
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./image/load
      DockerTag: python3.12-v1

Outputs:
  CreateFolderFunctionArn:
    Value: !GetAtt CreateFolderFunction.Arn
    Export:
      Name:
        CreateFolderFunctionArn

  DeleteFolderFunctionArn:
    Value: !GetAtt DeleteFolderFunction.Arn
    Export:
      Name:
        DeleteFolderFunctionArn

  GetFolderFunctionArn:
    Value: !GetAtt GetFolderFunction.Arn
    Export:
      Name:
        GetFolderFunctionArn

  UploadPhotoToFolderFunctionArn:
    Value: !GetAtt UploadPhotoToFolderFunction.Arn
    Export:
      Name:
        UploadPhotoToFolderFunctionArn